name: Azure Container Registry

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    env:
      NOME_IMAGEM: apicontagem-appinsights

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login no Azure Container Registry
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        login-server: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}

    - name: Build e Push no Azure Container Registry
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ env.NOME_IMAGEM }}:$GITHUB_RUN_NUMBER
        docker tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ env.NOME_IMAGEM }}:$GITHUB_RUN_NUMBER ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ env.NOME_IMAGEM }}:latest
        docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ env.NOME_IMAGEM }}
